-- Create doctors table
CREATE TABLE doctors (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    officeno VARCHAR(10) NOT NULL,
    specialization VARCHAR(100) NOT NULL,
    status ENUM('online', 'offline') DEFAULT 'offline',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert existing data
INSERT INTO doctors (id, name, email, password, officeno, specialization, status) VALUES
(1, 'م. اسراء العاصم', 'Israa Al-Aasem@zu.edu.jo', '123', '119-A', 'Computer Science', 'offline'),
(2, 'م. آيات الضروس', 'Ayat Al-Droos@zu.edu.jo', '123', '119-A', 'Computer Science', 'offline'),
(3, 'م. ديانا العمري', 'Diana Al-Omari@zu.edu.jo', '123', '119-A', 'Computer Science', 'offline'),
(4, 'م. نجوى ابو ميسمير', 'Najwa Abu Mismir@zu.edu.jo', '123', '119-A', 'Computer Science', 'offline'),
(5, 'د.هبة الله خطاب', 'Heba Allah Khattab@zu.edu.jo', '123', '147-A', 'Computer Science', 'offline'),
(6, 'نائب العميد أ.هايل خفاجة', 'Hael Khafaga@zu.edu.jo', '123', '151-A', 'Computer Science', 'offline'),
(7, 'د.محمد حسان', 'Mohammed Hassan@zu.edu.jo', '123', '152-A', 'Computer Science', 'online'),
(8, 'د. رائد الازايده', 'Raed Al-Azaydeh@zu.edu.jo', '123', '159-A', 'Computer Science', 'offline'),
(9, 'د. محمد الغانم', 'Mohammed Al-Ghanem@zu.edu.jo', '123', '161-A', 'Computer Science', 'offline'),
(10, 'د. حازم بدارنه', 'Hazem Badarneh@zu.edu.jo', '123', '162-A', 'Computer Science', 'offline'),
(11, 'د. هاني عمر', 'Hani Omar@zu.edu.jo', '123', '163-A', 'Computer Science', 'offline'),
(12, 'د. انور القطراوي', 'Anwar Qatrawi@zu.edu.jo', '123', '167-A', 'Computer Science', 'offline'),
(13, 'د. اسراء الحناوي', 'Esraa Henawi@zu.edu.jo', '123', '168-A', 'Computer Science', 'offline'),
(14, 'د. فؤاد الشريدة', 'Foaad Shrideh@zu.edu.jo', '123', '169-A', 'Computer Science', 'offline'),
(15, 'د. قتادة جوازنة', 'Qutada Jawazneh@zu.edu.jo', '123', '170-A', 'Computer Science', 'offline'),
(16, 'د. عدي المومني', 'Oday Momani@zu.edu.jo', '123', '171-A', 'Computer Science', 'offline'),
(17, 'د. عارف ابو عواد', 'Aref Abu Awwad@zu.edu.jo', '123', '172-A', 'Computer Science', 'offline'),
(18, 'د. يوسف هزايمه', 'Youssef Hazaimeh@zu.edu.jo', '123', '173-A', 'Computer Science', 'offline'),
(19, 'د. عصام النسور', 'Issam Al-Nsour@zu.edu.jo', '123', '177-A', 'Computer Science', 'offline'),
(20, 'د. احمد ابو رمان', 'Ahmed Abu Rman@zu.edu.jo', '123', '181-A', 'Computer Science', 'offline'),
(21, 'د. محمد الضمور', 'Mohammed Al-Damour@zu.edu.jo', '123', '182-A', 'Computer Science', 'offline'),
(22, 'د. عمر العظامات', 'Omar Al-Azamat@zu.edu.jo', '123', '183-A', 'Computer Science', 'offline'),
(23, 'د. محمد عربيات', 'Mohammed Arabiyat@zu.edu.jo', '123', '184-A', 'Computer Science', 'offline'),
(24, 'د. علاء الشيخ يوسف', 'Alaa Al-Sheikh Youssef@zu.edu.jo', '123', '356-A', 'Computer Science', 'offline'),
(25, 'د. محمود العساسفة', 'Mahmoud Al-Asasfeh@zu.edu.jo', '123', '358-A', 'Computer Science', 'offline'),
(26, 'د. سامي عسكر', 'Sami Askar@zu.edu.jo', '123', '361-A', 'Computer Science', 'offline'),
(27, 'د. مصعب قطيط', 'Mosaab Qatit@zu.edu.jo', '123', '362-A', 'Computer Science', 'offline'),
(28, 'د. نبيل الملي', 'Nabil Al-Mulli@zu.edu.jo', '123', '364-A', 'Computer Science', 'offline'),
(29, 'د. نضال يوسف', 'Nidal Youssef@zu.edu.jo', '123', '367-A', 'Computer Science', 'offline'),
(30, 'د. عبدالله القماز', 'Abdullah Al-Qammaz@zu.edu.jo', '123', '368-A', 'Computer Science', 'offline'),
(31, 'د.سهى عفانة', 'Suha Afana@zu.edu.jo', '123', '369-A', 'Computer Science', 'offline'),
(32, 'د. الياس جريسات', 'Elias Jreisat@zu.edu.jo', '123', '370-A', 'Computer Science', 'offline'),
(33, 'د. صلاح الدين بدران', 'Salah Al-Din Badran@zu.edu.jo', '123', '371-A', 'Computer Science', 'offline'),
(34, 'د. اياد الشحروري', 'Iyad Al-Shahruri@zu.edu.jo', '123', '372-A', 'Computer Science', 'offline'),
(35, 'د. فادي الجوازنة', 'Fadi Al-Jawazneh@zu.edu.jo', '123', '374-A', 'Computer Science', 'offline'),
(36, 'د. علاء بني بكر', 'Alaa Bani Bakr@zu.edu.jo', '123', '376-A', 'Computer Science', 'offline'),
(37, 'م. فاطمة حيمور', 'Fatima Haimour@zu.edu.jo', '123', '377-A', 'Computer Science', 'offline'),
(38, 'د. محمد الصياح', 'Mohammad Al-Sayyah@zu.edu.jo', '123', '380-A', 'Computer Science', 'offline'),
(39, 'د. رامي الطعاني', 'Rami Al-Taani@zu.edu.jo', '123', '381-A', 'Computer Science', 'offline'),
(40, 'د. علي ابو زيد', 'Ali Abu Zaid@zu.edu.jo', '123', '382-A', 'Computer Science', 'offline'),
(41, 'م. سهام حيمور', 'Siham Haimour@zu.edu.jo', '123', '15-B', 'Computer Science', 'offline'),
(42, 'د. رزين قدورة', 'Razeen Qaddoura@zu.edu.jo', '123', '102-B', 'Computer Science', 'offline'),
(43, 'د. محمد رسمي', 'Muhammad Rasmi@zu.edu.jo', '123', '104-B', 'Computer Science', 'offline'),
(44, 'د. آمنة العملة', 'Amna Al-Amleh@zu.edu.jo', '123', '110-B', 'Computer Science', 'offline'),
(45, 'د. حمزة الجواودة', 'Hamza Al-Jawawdeh@zu.edu.jo', '123', '114-B', 'Computer Science', 'offline'),
(46, 'م. هنادي بني حمد', 'Hanadi Bani Hamad@zu.edu.jo', '123', '118-B', 'Computer Science', 'offline'),
(47, 'م. غدير القهموس', 'Ghadeer Al-Qahmous@zu.edu.jo', '123', '118-B', 'Computer Science', 'offline'),
(48, 'م. الاء اسعد', 'Alaa Asaad@zu.edu.jo', '123', '118-B', 'Computer Science', 'offline'),
(49, 'م. منى القواقنة', 'Muna Al-Qawaqneh@zu.edu.jo', '123', '122-B', 'Computer Science', 'offline'),
(50, 'م. الاء الدهيثم', 'Alaa Al-Dahitham@zu.edu.jo', '123', '122-B', 'Computer Science', 'offline'),
(51, 'م. أميرة الذغمي', 'Amira Al-Dhaghmi@zu.edu.jo', '123', '122-B', 'Computer Science', 'offline'),
(52, 'ahmad admin', 'amedameen830@gmail.com', '$2y$10$7pwt0rcxt4tM4Uw/jczWGug8FZCYo83y4cgWOjor4Oa/GfrRsZvqm', '122-B', 'Computer Science', 'offline'); 